export const GET_BOOSTED = 'GET_BOOSTED';
export const GET_BOOSTED_SUCCESS = 'GET_BOOSTED_SUCCESS';
export const REFRESH_BOOSTED = 'REFRESH_BOOSTED';
export const CREATE_BOOSTED = 'CREATE_BOOSTED';
export const HIDE_AD_MODAL = 'HIDE_AD_MODAL';
