export const GET_RECOMMENDED_SUCCESS = 'GET_RECOMMENDED_SUCCESS';
export const GET_RECOMMENDED = 'GET_RECOMMENDED';
export const GET_MENTIONS_SUCCESS = 'GET_MENTIONS_SUCCESS';

export const REFRESH_POSTS = 'REFRESH_POSTS';
export const REFRESH_MENTIONS = 'REFRESH_MENTIONS';